--SOCIO
UPDATE SOCIO SET PUNTOS=11 WHERE ID_SOCIO = 20;
UPDATE SOCIO SET PUNTOS=321 WHERE ID_SOCIO = 21;
UPDATE SOCIO SET PUNTOS=21 WHERE ID_SOCIO = 22;
UPDATE SOCIO SET PUNTOS=645 WHERE ID_SOCIO = 23;
UPDATE SOCIO SET PUNTOS=283 WHERE ID_SOCIO = 24;
UPDATE SOCIO SET PUNTOS=89 WHERE ID_SOCIO = 25;
UPDATE SOCIO SET PUNTOS=0 WHERE ID_SOCIO = 26;
UPDATE SOCIO SET PUNTOS=432 WHERE ID_SOCIO = 27;
UPDATE SOCIO SET PUNTOS=999 WHERE ID_SOCIO = 28;
UPDATE SOCIO SET PUNTOS=432 WHERE ID_SOCIO = 29;

-- CLIENTE
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 20;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 21;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 22;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 23;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 24;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 25;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 26;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 27;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 28;
UPDATE CLIENTE SET NOMBRE='JORGE' WHERE ID_CLIENTE = 29;

-- MEMBRESIA
UPDATE MEMBRESIA SET COSTO=50 WHERE ID_MEMBRESIA=51;
UPDATE MEMBRESIA SET COSTO=32 WHERE ID_MEMBRESIA=52;
UPDATE MEMBRESIA SET COSTO=566 WHERE ID_MEMBRESIA=53;
UPDATE MEMBRESIA SET COSTO=123 WHERE ID_MEMBRESIA=54;
UPDATE MEMBRESIA SET COSTO=45 WHERE ID_MEMBRESIA=55;
UPDATE MEMBRESIA SET COSTO=12 WHERE ID_MEMBRESIA=56;
UPDATE MEMBRESIA SET COSTO=0 WHERE ID_MEMBRESIA=57;
UPDATE MEMBRESIA SET COSTO=100 WHERE ID_MEMBRESIA=58;
UPDATE MEMBRESIA SET COSTO=800 WHERE ID_MEMBRESIA=59;
UPDATE MEMBRESIA SET COSTO=250 WHERE ID_MEMBRESIA=60;