-- SOCIO
DELETE FROM SOCIO WHERE ID_SOCIO = 1;
DELETE FROM SOCIO WHERE ID_SOCIO = 2;
DELETE FROM SOCIO WHERE ID_SOCIO = 3;
DELETE FROM SOCIO WHERE ID_SOCIO = 4;
DELETE FROM SOCIO WHERE ID_SOCIO = 5;
DELETE FROM SOCIO WHERE ID_SOCIO = 6;
DELETE FROM SOCIO WHERE ID_SOCIO = 7;
DELETE FROM SOCIO WHERE ID_SOCIO = 8;
DELETE FROM SOCIO WHERE ID_SOCIO = 9;
DELETE FROM SOCIO WHERE ID_SOCIO = 10;

-- PERSONA_CONTACTO
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Cade';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Sacha';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Keefe';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Vladimir';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Nichole';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Rashad';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Gil';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Cara';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Ivana';
DELETE FROM PERSONA_CONTACTO WHERE NOMBRE = 'Felicia';

-- CLIENTE
DELETE FROM CLIENTE WHERE ID_CLIENTE = 1;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 2;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 3;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 4;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 5;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 6;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 7;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 8;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 9;
DELETE FROM CLIENTE WHERE ID_CLIENTE = 10;

-- ENTRENADOR
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 1;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 2;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 3;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 4;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 5;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 6;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 7;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 8;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 9;
DELETE FROM ENTRENADOR WHERE ID_EMPLEADO = 10;

-- DIRECCION
DELETE FROM DIRECCION WHERE ID_DIRECCION = 1;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 2;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 3;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 4;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 5;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 6;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 7;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 8;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 9;
DELETE FROM DIRECCION WHERE ID_DIRECCION = 10;

-- MEMBRESIA
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 1;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 2;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 3;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 4;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 5;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 6;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 7;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 8;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 9;
DELETE FROM MEMBRESIA WHERE ID_MEMBRESIA = 10;

-- MEMBRESIA
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 1;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 2;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 3;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 4;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 5;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 6;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 7;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 8;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 9;
DELETE FROM MEMBRESIA_BASICA WHERE ID_MEMBRESIA = 10;

-- MEMBRESIA_PLUS
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 1;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 2;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 3;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 4;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 5;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 6;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 7;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 8;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 9;
DELETE FROM MEMBRESIA_PLUS WHERE ID_MEMBRESIA = 10;

-- MEMBRESIA_PREMIUM
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 1;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 2;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 3;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 4;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 5;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 6;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 7;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 8;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 9;
DELETE FROM MEMBRESIA_PREMIUM WHERE ID_MEMBRESIA = 10;

-- CLASE
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'Duis risus';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'velit eget';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'molestie arcu.';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'diam eu';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'nec, diam.';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'facilisi. Sed';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'Integer aliquam';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'sed dictum';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'vel, mauris.';
DELETE FROM CLASE WHERE NOMBRE_CLASE = 'lacus. Ut';

-- PRODUCTO
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'vestibulum. Mauris';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'lobortis, nisi';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'tincidunt nibh.';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'orci luctus';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'faucibus orci';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'nulla. Integer';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'varius et,';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'Sed malesuada';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'Fusce aliquam,';
DELETE FROM PRODUCTO WHERE NOMBRE_PRODUCTO = 'ac facilisis';

-- LAS DEMAS ENTIDADES SON RELACIONES CON LLAVES FORANEAS EN CASCADA
-- AS QUE DEBERIAN DE ELIMINARSE EN CUANTO SE ELIMINAN ESTAS