-- CUMPLE
INSERT INTO SOCIO (ID_SOCIO,NOMBRE,AP_PATERNO,AP_MATERNO,EMAIL,EDAD,SEXO,TELEFONO,FEC_NAC,PERSONA_CONTACTO,PUNTOS) VALUES (200, NULL, 'Pena','Nieves','et.libero.Proin@nonmassanon.net','17-09-02','FEMENINO','0313936518','18-04-13','Gloria',292);
-- NO CUMPLE
INSERT INTO SOCIO (ID_SOCIO,NOMBRE,AP_PATERNO,AP_MATERNO,EMAIL,EDAD,SEXO,TELEFONO,FEC_NAC,PERSONA_CONTACTO,PUNTOS) VALUES (200, NULL, 'Pena','Nieves','et.libero.Proin@nonmassanon.net','17-09-02','F','0313936518','18-04-13','Gloria',292);

-- Y ES EL MISMO CASO PARA SOCIO, CLIENTE Y ENTRENADOR

-- CUMPLE
INSERT INTO DIRECCION (ID_DIRECCION,CALLE,NUMERO,COLONIA,CP,DELEGACION) VALUES (1,'2786 Donec Street',103,'AN',56088,'Jaén');
-- NO CUMPLE
INSERT INTO DIRECCION (ID_DIRECCION,CALLE,NUMERO,COLONIA,CP,DELEGACION) VALUES (1,'2786 Donec Street',103,'AN',156088,'Jaén');