-- RESTRICCIONES TABLA SOCIO
ALTER TABLE SOCIO ADD CONSTRAINT PK_SOCIO PRIMARY KEY (ID_SOCIO);
ALTER TABLE SOCIO ADD CONSTRAINT CK_SOCIO_NOMBRE CHECK (NOMBRE IS NOT NULL);
ALTER TABLE SOCIO ADD CONSTRAINT CK_SOCIO_SEXO CHECK(SEXO IN ('MASCULINO', 'FEMENINO'));

-- RESTRICCIONES TABLA PERSONA_CONTACTO
ALTER TABLE PERSONA_CONTACTO ADD CONSTRAINT PK_PERSONA_CONTACTO PRIMARY KEY (NOMBRE);

-- RESTRICCIONES TABLA CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_NOMBRE CHECK (NOMBRE IS NOT NULL);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_SEXO CHECK(SEXO IN ('MASCULINO', 'FEMENINO'));

-- RESTRICCIONES TABLA DIRECCION
ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (ID_DIRECCION);
ALTER TABLE DIRECCION ADD CONSTRAINT CK_CP CHECK(CP <= 99999);

-- RESTRICCIONES TABLA ENTRENADOR
ALTER TABLE ENTRENADOR ADD CONSTRAINT PK_ENTRENADOR PRIMARY KEY (ID_EMPLEADO);
ALTER TABLE ENTRENADOR ADD CONSTRAINT CK_ENTRENADOR_NOMBRE CHECK (NOMBRE IS NOT NULL);
ALTER TABLE ENTRENADOR ADD CONSTRAINT CK_ENTRENADOR_SEXO CHECK(SEXO IN ('MASCULINO', 'FEMENINO'));
ALTER TABLE ENTRENADOR ADD CONSTRAINT FK_ENTRENADOR_DIRECICON FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION);

-- RESTRICCIONES TABLA MEMBRESIA
ALTER TABLE MEMBRESIA ADD CONSTRAINT PK_MEMBRESIA PRIMARY KEY (ID_MEMBRESIA);
ALTER TABLE MEMBRESIA ADD CONSTRAINT FK_MEMBRESIA_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO) ON DELETE CASCADE;

-- RESTRICCIONES TABLA MEMBRESIA_BASICA
ALTER TABLE MEMBRESIA_BASICA ADD CONSTRAINT PK_MEMBRESIA_BASICA PRIMARY KEY (ID_MEMBRESIA);
ALTER TABLE MEMBRESIA_BASICA ADD CONSTRAINT FK_MEMBRESIA_BASICA FOREIGN KEY (ID_MEMBRESIA) REFERENCES MEMBRESIA(ID_MEMBRESIA) ON DELETE CASCADE;

-- RESTRICCIONES TABLA MEMBRESIA_PLUS
ALTER TABLE MEMBRESIA_PLUS ADD CONSTRAINT PK_MEMBRESIA_PLUS PRIMARY KEY (ID_MEMBRESIA);
ALTER TABLE MEMBRESIA_PLUS ADD CONSTRAINT FK_MEMBRESIA_PLUS FOREIGN KEY (ID_MEMBRESIA) REFERENCES MEMBRESIA(ID_MEMBRESIA) ON DELETE CASCADE;

-- RESTRICCIONES TABLA MEMBRESIA_PREMIUM
ALTER TABLE MEMBRESIA_PREMIUM ADD CONSTRAINT PK_MEMBRESIA_PREMIUM PRIMARY KEY (ID_MEMBRESIA);
ALTER TABLE MEMBRESIA_PREMIUM ADD CONSTRAINT FK_MEMBRESIA_PREMIUM FOREIGN KEY (ID_MEMBRESIA) REFERENCES MEMBRESIA(ID_MEMBRESIA) ON DELETE CASCADE;

-- RESTRICCIONES TABLA CLASE
ALTER TABLE CLASE ADD CONSTRAINT PK_CLASE PRIMARY KEY (ID_CLASE);

-- RESTRICCIONES TABLA PRODUCTO
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO); 

-- RESTRICCIONES TABLA TENER
ALTER TABLE TENER ADD CONSTRAINT PK_TENER PRIMARY KEY (ID_MEMBRESIA, ID_SOCIO);
ALTER TABLE TENER ADD CONSTRAINT FK_TENER_MREMBRESIA FOREIGN KEY (ID_MEMBRESIA) REFERENCES MEMBRESIA(ID_MEMBRESIA) ON DELETE CASCADE;
ALTER TABLE TENER ADD CONSTRAINT FK_TENER_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO) ON DELETE CASCADE;

-- RESTRICCIONES TABLA TOMAR_CLASE_SOCIO
ALTER TABLE TOMAR_CLASE_SOCIO ADD CONSTRAINT PK_TOMARCLASESOCIO PRIMARY KEY (ID_CLASE, ID_SOCIO);
ALTER TABLE TOMAR_CLASE_SOCIO ADD CONSTRAINT FK_TOMARCLASESOCIO_IDCLASE FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE;
ALTER TABLE TOMAR_CLASE_SOCIO ADD CONSTRAINT FK_TOMARCLASESOCIO_IDSOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO) ON DELETE CASCADE;

-- RESTRICCIONES TABLA TOMAR_CLASE_CLIENTE
ALTER TABLE TOMAR_CLASE_CLIENTE ADD CONSTRAINT PK_TOMARCLASECLIENTE PRIMARY KEY (ID_CLASE, ID_CLIENTE);
ALTER TABLE TOMAR_CLASE_CLIENTE ADD CONSTRAINT FK_TOMARCLASECLIENTE_IDCLASE FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE;
ALTER TABLE TOMAR_CLASE_CLIENTE ADD CONSTRAINT FK_TOMARCLASECLIENTE_IDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE;

-- RESTRICCIONES TABLA COMPRAR_SOCIO
ALTER TABLE COMPRAR_SOCIO ADD CONSTRAINT PK_COMPRARSOCIO PRIMARY KEY (ID_PRODUCTO, ID_SOCIO);
ALTER TABLE COMPRAR_SOCIO ADD CONSTRAINT FK_COMPRARSOCIO_PROD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO) ON DELETE CASCADE;
ALTER TABLE COMPRAR_SOCIO ADD CONSTRAINT FK_COMPRARSOCIO_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO) ON DELETE CASCADE;

-- RESTRICCIONES TABLA COMPRAR_CLIENTE
ALTER TABLE COMPRAR_CLIENTE ADD CONSTRAINT PK_COMPRARCLIENTE PRIMARY KEY (ID_PRODUCTO, ID_CLIENTE);
ALTER TABLE COMPRAR_CLIENTE ADD CONSTRAINT FK_COMPRARCLIENTE_PROD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO) ON DELETE CASCADE;
ALTER TABLE COMPRAR_CLIENTE ADD CONSTRAINT FK_COMPRARCLIENTE_SOCIO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE;

-- RESTRICCIONES TABLA IMPARTIR_CLASE
ALTER TABLE IMPARTIR_CLASE ADD CONSTRAINT PK_IMPARTIR_CLASE PRIMARY KEY (ID_CLASE, ID_EMPLEADO);
ALTER TABLE IMPARTIR_CLASE ADD CONSTRAINT FK_IMPARTIR_CLASE_IDCLASE FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID_CLASE) ON DELETE CASCADE;
ALTER TABLE IMPARTIR_CLASE ADD CONSTRAINT FK_IMPARTIR_CLASE_IDEMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES ENTRENADOR(ID_EMPLEADO) ON DELETE CASCADE;
