-- Producto Cartesiano
-- El nombre completo de los instructores y su direccion
SELECT NOMBRE, AP_PATERNO, AP_MATERNO, CALLE, NUMERO, COLONIA
FROM ENTRENADOR, DIRECCION;

-- ALGUN TIPO DE JOIN
-- Todas las clases impartidas
SELECT *
FROM CLASE JOIN IMPARTIR_CLASE
ON CLASE.ID_CLASE = IMPARTIR_CLASE.ID_CLASE;

-- USANDO UNION
--Clientes y socios que han comprado productos y que tengan edades entre 18 y 35 años 
SELECT NOMBRE, AP_PATERNO, NOMBRE_PRODUCTO
FROM (SOCIO FULL OUTER JOIN COMPRAR_SOCIO
ON (SOCIO.ID_SOCIO = COMPRAR_SOCIO.ID_SOCIO)) FULL OUTER JOIN PRODUCTO
ON COMPRAR_SOCIO.ID_PRODUCTO = PRODUCTO.ID_PRODUCTO
AND EDAD BETWEEN 20 AND 30
UNION
SELECT NOMBRE, AP_PATERNO, NOMBRE_PRODUCTO
FROM (CLIENTE FULL OUTER JOIN COMPRAR_CLIENTE
ON (CLIENTE.ID_CLIENTE = COMPRAR_CLIENTE.ID_CLIENTE)) FULL OUTER JOIN PRODUCTO
ON COMPRAR_CLIENTE.ID_PRODUCTO = PRODUCTO.ID_PRODUCTO
AND EDAD BETWEEN 20 AND 30;

-- USANDO INTERSECTION
-- Clientes que ademas son socios que son mayores de 18 años y sus clases
SELECT NOMBRE, AP_PATERNO, AP_MATERNO, NOMBRE_CLASE
FROM (SOCIO FULL OUTER JOIN TOMAR_CLASE_SOCIO
ON SOCIO.ID_SOCIO = TOMAR_CLASE_SOCIO.ID_SOCIO) FULL OUTER JOIN CLASE
ON TOMAR_CLASE_SOCIO.ID_CLASE = CLASE.ID_CLASE
AND EDAD < 18
INTERSECT
SELECT NOMBRE, AP_PATERNO, AP_MATERNO, NOMBRE_CLASE
FROM (CLIENTE FULL OUTER JOIN TOMAR_CLASE_CLIENTE
ON CLIENTE.ID_CLIENTE = TOMAR_CLASE_CLIENTE.ID_CLIENTE) FULL OUTER JOIN CLASE
ON TOMAR_CLASE_CLIENTE.ID_CLASE = CLASE.ID_CLASE
AND EDAD < 18;

-- USANDO MINUS
-- Los clientes hombres que asisten a clase de Zumba pero no de Box
SELECT NOMBRE, SEXO, NOMBRE_CLASE
FROM (SOCIO FULL OUTER JOIN TOMAR_CLASE_SOCIO
ON SOCIO.ID_SOCIO = TOMAR_CLASE_SOCIO.ID_SOCIO) FULL OUTER JOIN CLASE
ON TOMAR_CLASE_SOCIO.ID_CLASE = CLASE.ID_CLASE
WHERE SEXO='MASCULINO'
AND NOMBRE_CLASE = 'ZUMBA'
MINUS
SELECT NOMBRE, SEXO, NOMBRE_CLASE
FROM (SOCIO FULL OUTER JOIN TOMAR_CLASE_SOCIO
ON SOCIO.ID_SOCIO = TOMAR_CLASE_SOCIO.ID_SOCIO) FULL OUTER JOIN CLASE
ON TOMAR_CLASE_SOCIO.ID_CLASE = CLASE.ID_CLASE
WHERE SEXO='MASCULINO'
AND NOMBRE_CLASE = 'BOX';
