-- PUNTO EXTRA MULTAS

-- PARTE A

CREATE TABLE DIRECCION(
    ID NUMBER(8) PRIMARY KEY,
    ESTADO VARCHAR(25) NOT NULL,
    DEL_MUN VARCHAR(25) NOT NULL,
    COLONIA VARCHAR(25),
    CALLE VARCHAR(25) NOT NULL,
    REFERENCIA VARCHAR(25),
    CALLE1 VARCHAR(25),
    CALLE2 VARCHAR(25)
);

CREATE TABLE ARMADORA(
	ID_NOMBRE NUMBER(8) PRIMARY KEY,
	ID_DIRECCION NUMBER(8),
	CONSTRAINT FK_DIRECCION_ARMADORA FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID) 
);

CREATE TABLE MARCA(
	NOMBRE VARCHAR(50) PRIMARY KEY,
	ID_ARMADORA NUMBER(8),
    CONSTRAINT FK_ID_ARMADORA_MARCA FOREIGN KEY (ID_ARMADORA) REFERENCES ARMADORA(ID_NOMBRE)
);

CREATE TABLE PROPIETARIO(
    RFC CHAR(13) PRIMARY KEY,
    FEC_NAC DATE,
    NOMBRE VARCHAR(20) NOT NULL,
    APATERNO VARCHAR(20),
    AMATERNO VARCHAR(20),
    ID_DIRECCION NUMBER(8),
    CONSTRAINT CHECK_RFC_PROPIETARIO CHECK (LENGTH(RFC) = 13),
    CONSTRAINT FK_DIRECCION_PROPIETARIO FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID)
);

CREATE TABLE MODELO(
    NOMBRE VARCHAR(25),
    VERSION VARCHAR(15),
    AÑO NUMBER(4),
    LITROS_MOTOR NUMBER(3),
    CILINDROS NUMBER(2),
    PASAJEROS NUMBER(2),
    TANQUE VARCHAR(25),
    NOMBRE_MARCA VARCHAR(25),
    PRIMARY KEY(NOMBRE, VERSION),
    CONSTRAINT FK_NOMBRE_MARCA_MODELO FOREIGN KEY (NOMBRE_MARCA) REFERENCES MARCA(NOMBRE)
);

CREATE TABLE AUTO(
    NO_MOTOR NUMBER(8) PRIMARY KEY,
    NOMBRE VARCHAR(25),
    MODELO NUMBER(4),
    VERSION_MODELO VARCHAR(20)
);

CREATE TABLE INFRACCION(
    NO_EXP NUMBER(8) PRIMARY KEY,
    ARTICULO NUMBER(3),
    COSTO DECIMAL(5,2)
);

CREATE TABLE AGENTE(
    NUM_AGENTE NUMBER(8) PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APATERNO VARCHAR(20),
    AMATERNO VARCHAR(20)
);

CREATE TABLE PONE(
    NUM_AGENTE NUMBER(8),
    NO_EXP NUMBER(8),
    PRIMARY KEY(NUM_AGENTE, NO_EXP),
    CONSTRAINT FK_NUM_AGENTE_PONE FOREIGN KEY (NUM_AGENTE) REFERENCES AGENTE(NUM_AGENTE),
    CONSTRAINT FK_NO_EXP_PONE FOREIGN KEY (NO_EXP) REFERENCES INFRACCION(NO_EXP)
);

CREATE TABLE ADQUIRIR(
  RFC VARCHAR(13),
  NO_MOTOR NUMBER(8),
  FEC_INICIO DATE,
  FEC_FIN DATE,
  PRIMARY KEY(RFC, NO_MOTOR),
  CONSTRAINT CHECK_RFC_ADQUIRIR CHECK (LENGTH(RFC) = 13),
  CONSTRAINT FK_NO_MOTOR_ADQUIRIR FOREIGN KEY (NO_MOTOR) REFERENCES AUTO(NO_MOTOR) 
);

CREATE TABLE TARJETA(
    NUMERO NUMBER(8) PRIMARY KEY,
    VIGENCIA DATE,
    FEC_VENCIMIENTO DATE NOT NULL,
    PLACA VARCHAR(6),
    NO_MOTOR NUMBER(8),
    CONSTRAINT FK_NO_MOTOR_TARJETA FOREIGN KEY (NO_MOTOR) REFERENCES AUTO(NO_MOTOR)
);

CREATE TABLE LICENCIA(
    NUMERO NUMBER(8) PRIMARY KEY,
    TIPO CHAR(1),
    VIGENCIA DATE,
    FEC_VENCIMIENTO DATE NOT NULL,
    RFC VARCHAR(13),
    CONSTRAINT CHECK_RFC_LICENCIA CHECK (LENGTH(RFC) = 13)
);

CREATE TABLE MULTA(
    NO_LIC NUMBER(8),
    NO_TARJETA NUMBER(8),
    ID_DIRECCION NUMBER(8),
    NO_EXP NUMBER(8),
    FECHA DATE,
    PRIMARY KEY(NO_LIC, NO_TARJETA, ID_DIRECCION, NO_EXP),
    CONSTRAINT FK_NO_LIC_MULTA FOREIGN KEY (NO_LIC) REFERENCES LICENCIA(NUMERO),
    CONSTRAINT FK_NO_TARJETA_MULTA FOREIGN KEY (NO_TARJETA) REFERENCES TARJETA(NUMERO),
    CONSTRAINT FK_DIRECCION_MULTA FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID),
    CONSTRAINT FK_NO_EXP_MULTA FOREIGN KEY (NO_EXP) REFERENCES INFRACCION(NO_EXP)
);

-- PARTE B

-- AGREGAR GENERO
ALTER TABLE PROPIETARIO
ADD  GENERO VARCHAR(9) CHECK(GENERO IN ('MASCULINO', 'FEMENINO'));

-- ELIMINAR TANQUE
ALTER TABLE MODELO
DROP COLUMN TANQUE;

-- YA QUE MODELO NO ALMACENA NO_MOTOR CAMBIAMOS EL DE AUTO
ALTER TABLE AUTO MODIFY (NO_MOTOR VARCHAR(20));

-- RENOMBRA PROPIETARIO POR DUEÑO
ALTER TABLE PROPIETARIO RENAME TO DUEÑO;

/* TO DROP ALL THE TABLES
DROP TABLE ARMADORA;
DROP TABLE MARCA;
DROP TABLE DIRECCION;
DROP TABLE PROPIETARIO;
DROP TABLE MODELO;
DROP TABLE AUTO;
DROP TABLE INFRACCION;
DROP TABLE AGENTE;
DROP TABLE PONE;
DROP TABLE MULTA;
DROP TABLE ADQUIRIR;
DROP TABLE TARJETA;
DROP TABLE LICENCIA;
*/