/**
 * CREACION TABLAS TACOSTE
 */

--NO OLVIDAR EL CLIENTE DEFAULT
-- TABLA CLIENTE
CREATE TABLE CLIENTE(
    NOMBRE VARCHAR(25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    SEXO VARCHAR(9),
    CALLE VARCHAR(50),
    NUMERO_EXT NUMBER,
    NUMERO_INT NUMBER,
    COLONIA VARCHAR(50),
    ESTADO VARCHAR(30),
    CP NUMBER(5,0),
    TELEFONO NUMBER(10),
    EMAIL VARCHAR(80),
    CURP VARCHAR(18)
);

-- TABLA PROGRAMA TAQUERO MUCHO
CREATE TABLE TAQUERO_MUCHO(
    ID_TARJETA NUMBER,
    CURP VARCHAR(18),
    PUNTOS NUMBER
);

-- TABLA SALSAS
CREATE TABLE SALSA(
    NOMBRE VARCHAR(30),
    INGREDIENTES VARCHAR(200),
    -- PICOR MAXIMO LONGITUD: EXTREMO (7 CARACTERES)
    PICOR VARCHAR(7),
    RECOMENDACIONES VARCHAR(200)
);

-- TABLA RELACION: CLIENTE - COMPRAR - SALSA
CREATE TABLE COMPRAR_SALSA(
    NOMBRE VARCHAR(30),
    CURP VARCHAR(18),
    FECHA DATE,
    -- OPCION SI/NO, LA DIRECCION SE OBTIENE DEL CLIENTE
    A_DOMICILIO VARCHAR(2)
);

-- TABLA CONSUMIBLES
CREATE TABLE CONSUMIBLE(
    ID_CONSUMIBLE NUMBER,
    NOMBRE VARCHAR(80),
    DESCRIPCION VARCHAR(200),
    -- DECIMAL(5, 2) PERMITE AGREGAR DECIMALES
    PRECIO DECIMAL(5,2),
    CANTIDAD NUMBER
);


-- TABLA SECCION ENTRADAS
CREATE TABLE ENTRADAS(
    ID_CONSUMIBLE NUMBER
);

--TABLA SECCION DEL CAZO
CREATE TABLE DEL_CAZO(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION SOPES Y HUARACHES
CREATE TABLE SOPES_HUARACHES(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION ENCHILADAS
CREATE TABLE ENCHILADAS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION QUESOS
CREATE TABLE QUESOS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION ENSALADAS
CREATE TABLE ENSALADAS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION GRINGAS, QUECAS Y VOLCANES
CREATE TABLE GRINGAS_QUECAS_VOLCANES(
    ID_CONSUMIBLE NUMBER 
);

-- TABLA SECCION ALAMBRES
CREATE TABLE ALAMBRES(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION HAMBURGUESAS
CREATE TABLE HAMBURGUESAS(
    ID_CONSUMIBLE NUMBER 
);

-- TABLA SECCION TACOS
CREATE TABLE TACOS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION TORTAS
CREATE TABLE TORTAS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION BEBIDAS
CREATE TABLE BEBIDAS(
    ID_CONSUMIBLE NUMBER
);

-- TABLA SECCION POSTRES
CREATE TABLE POSTRES(
    ID_CONSUMIBLE NUMBER
);

-- TABLA RELACION CLIENTE-CONSUMIR-CONSUMIBLE
CREATE TABLE CONSUMIR_CLIENTE(
    ID_CONSUMIBLE NUMBER,
    CURP VARCHAR(18),
    FECHA DATE,
    -- OPCION SI/NO, LA DIRECCION SE OBTIENE DEL CLIENTE
    A_DOMICILIO VARCHAR(2)
);

-- NO HAY RELACIONES ENTRE CLIENTES Y EMPLEADOS YA QUE ESTOS NO RECIBEN COMISIONES
-- POR VENTAS EN EL TRABAJO, TODOS TRABAJAN FELIZMENTE SIN PELEARSE

-- TABLA EMPLEADO
CREATE TABLE EMPLEADO(
    NOMBRE VARCHAR(25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    SEXO VARCHAR(9),
    CALLE VARCHAR(50),
    NUMERO_EXT NUMBER,
    NUMERO_INT NUMBER,
    COLONIA VARCHAR(50),
    ESTADO VARCHAR(30),
    CP NUMBER(5,0),
    TELEFONO NUMBER(10),
    EMAIL VARCHAR(80),
    CURP VARCHAR(18)
);

-- TABLA EMPLEADO PARRILLERO
CREATE TABLE PARRILLERO(
    CURP VARCHAR(18)
);

-- TABLA EMPLEADO TAQUERO
CREATE TABLE TAQUERO(
    CURP VARCHAR(18)
);

-- TABLE EMPLEADO MESERO
CREATE TABLE MESERO(
    CURP VARCHAR(18)
);

-- TABLA EMPLEADO CAJERO
CREATE TABLE CAJERO(
    CURP VARCHAR(18)
);

-- TABLA EMPLEADO TORTILLERO
CREATE TABLE TORTILLERO(
    CURP VARCHAR(18)
);

-- TABLE EMPLEADO REPARTIDOR
CREATE TABLE REPARTIDOR(
    CURP VARCHAR(18),
    LICENCIA NUMBER,
    TRANSPORTE VARCHAR(11)
);

-- TABLA SUCURSAL
CREATE TABLE SUCURSAL(
    NOMBRE VARCHAR(25),
    ID_SUCURSAL NUMBER
    
);

-- TABLA RELACION EMPLEADO- TRABAJA - SUCURSAL
CREATE TABLE TRABAJAR_SUCURSAL(
    CURP VARCHAR(18),
    ID_SUCURSAL NUMBER
);

--TABLA PRODUCTO
CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    FECHA_COMPRA DATE,
    FECHA_CADUCIDAD DATE,
    UNIDADES_INVENTARIO NUMBER,
    MARCA VARCHAR(40),
    PRECIO DECIMAL(5,2),
    PROVEEDOR VARCHAR(40)
);

-- TRABLA RELACION SUCURSAL - TENER - PRODUCTO
CREATE TABLE TENER_PRODUCTO(
    ID_SUCURSAL NUMBER,
    ID_PRODUCTO NUMBER
);