/**
 * RESTRICCIONES DE TACOSTE 
 */

-- RESTRICCIONES TABLA CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CURP);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_NOMBRE CHECK (NOMBRE IS NOT NULL);
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_APP_PATERNO CHECK (AP_PATERNO IS NOT NULL);
-- NO IMPORTA EL APELLIDO MATERNO PORQUE PUEDE SER NULO
ALTER TABLE CLIENTE ADD CONSTRAINT CK_CLIENTE_SEXO CHECK(SEXO IN ('MASCULINO', 'FEMENINO'));

-- RESTRICCIONES TABLA TAQUERO_MUCHO
ALTER TABLE TAQUERO_MUCHO ADD CONSTRAINT PK_TAQUERO_MUCHO PRIMARY KEY (ID_TARJETA);
ALTER TABLE TAQUERO_MUCHO ADD CONSTRAINT FK_CURP FOREIGN KEY (CURP) REFERENCES CLIENTE(CURP) ON DELETE CASCADE;

-- RESTRICCIONES TABLA SALSA
ALTER TABLE SALSA ADD CONSTRAINT PK_SALSA PRIMARY KEY (NOMBRE);
ALTER TABLE SALSA ADD CONSTRAINT CK_PICOR CHECK (PICOR IN ('DULCE', 'BAJO', 'MEDIO', 'ALTO', 'EXTREMO'));

-- RESTRICCIONES TABLA COMPRAR_SALSA
ALTER TABLE COMPRAR_SALSA ADD CONSTRAINT PK_COM_SALSA PRIMARY KEY (NOMBRE, CURP);
ALTER TABLE COMPRAR_SALSA ADD CONSTRAINT FK_COM_SALSA_NOMBRE FOREIGN KEY (NOMBRE) REFERENCES SALSA(NOMBRE);
ALTER TABLE COMPRAR_SALSA ADD CONSTRAINT FK_COM_SALSA_CURP FOREIGN KEY (CURP) REFERENCES CLIENTE(CURP);
ALTER TABLE COMPRAR_SALSA ADD CONSTRAINT CK_COM_SALSA_DOM CHECK(A_DOMICILIO IN ('SI', 'NO'));

-- RESTRICCIONES TABLA CONSUMIBLE
ALTER TABLE CONSUMIBLE ADD CONSTRAINT PK_CONSUMIBLE PRIMARY KEY (ID_CONSUMIBLE);

-- RESTRICCIONES TABLA ENTRADAS
ALTER TABLE ENTRADAS ADD CONSTRAINT PK_ENTRADAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE ENTRADAS ADD CONSTRAINT FK_ENTRADAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA DEL_CAZO
ALTER TABLE DEL_CAZO ADD CONSTRAINT PK_DELCAZO PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE DEL_CAZO ADD CONSTRAINT FK_DEL_CAZO FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

--RESTRICCIONES TABLA SOPES_HUARACHES
ALTER TABLE SOPES_HUARACHES ADD CONSTRAINT PK_SP_HUAR PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE SOPES_HUARACHES ADD CONSTRAINT FK_SP_HUAR FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA ENCHILADAS
ALTER TABLE ENCHILADAS ADD CONSTRAINT PK_ENCHILADAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE ENCHILADAS ADD CONSTRAINT FK_ENCHILADAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA QUESOS
ALTER TABLE QUESOS ADD CONSTRAINT PK_QUESOS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE QUESOS ADD CONSTRAINT FK_QUESOS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA ENSALADAS
ALTER TABLE ENSALADAS ADD CONSTRAINT PK_ENSALADAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE ENSALADAS ADD CONSTRAINT FK_ENSALADAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA GRINGAS_QUECAS_VOLCANES
ALTER TABLE GRINGAS_QUECAS_VOLCANES ADD CONSTRAINT PK_GR_QC_VL PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE GRINGAS_QUECAS_VOLCANES ADD CONSTRAINT FK_GR_QC_VL FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

--RESTRICCIONES TABLA ALAMBRES
ALTER TABLE ALAMBRES ADD CONSTRAINT PK_ALAMBRES PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE ALAMBRES ADD CONSTRAINT FK_ALAMBRES FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA HAMBURGUESAS
ALTER TABLE HAMBURGUESAS ADD CONSTRAINT PK_HAMBURGUESAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE HAMBURGUESAS ADD CONSTRAINT FK_HAMBURGUESAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA TACOS
ALTER TABLE TACOS ADD CONSTRAINT PK_TACOS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE TACOS ADD CONSTRAINT FK_TACOS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA TORTAS
ALTER TABLE TORTAS ADD CONSTRAINT PK_TORTAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE TORTAS ADD CONSTRAINT FK_TORTAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA BEBIDAS
ALTER TABLE BEBIDAS ADD CONSTRAINT PK_BEBIDAS PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE BEBIDAS ADD CONSTRAINT FK_BEBIDAS FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA POSTRES
ALTER TABLE POSTRES ADD CONSTRAINT PK_POSTRES PRIMARY KEY (ID_CONSUMIBLE);
ALTER TABLE POSTRES ADD CONSTRAINT FK_POSTRES FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);

-- RESTRICCIONES TABLA CONSUMIR_CLIENTE
ALTER TABLE CONSUMIR_CLIENTE ADD CONSTRAINT PK_CON_CLIENTE PRIMARY KEY (ID_CONSUMIBLE, CURP);
ALTER TABLE CONSUMIR_CLIENTE ADD CONSTRAINT FK_CON_CLIENTE_ID FOREIGN KEY (ID_CONSUMIBLE) REFERENCES CONSUMIBLE(ID_CONSUMIBLE);
ALTER TABLE CONSUMIR_CLIENTE ADD CONSTRAINT FK_CON_CLIENTE_CURP FOREIGN KEY (CURP) REFERENCES CLIENTE(CURP);
ALTER TABLE CONSUMIR_CLIENTE ADD CONSTRAINT CK_CON_CLIENTE_DOM CHECK(A_DOMICILIO IN ('SI', 'NO'));

-- RESTRICCIONES TABLA EMPLEADO
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CURP);
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_EMPLEADO_NOMBRE CHECK (NOMBRE IS NOT NULL);
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_EMPLEADO_APP_PATERNO CHECK (AP_PATERNO IS NOT NULL);
-- NO IMPORTA EL APELLIDO MATERNO PORQUE PUEDE SER NULO
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_EMPLEADO_SEXO CHECK(SEXO IN ('MASCULINO', 'FEMENINO'));

-- COMO LAS INSERCIONES SE VAN A HACER EN AMBAS TABLAS, BASTA CON QUE CUMPLA LAS RESTRICCIONES PARA EMPLEADO
-- PARA QUE PUEDA ENTRAR EN EL TIPO DE EMPLEADO, TODO ESTO CON EL FIN DE EVITAR REDUNDANCIA

-- RESTRICCIONES TABLA EMPLEADO PARRILLERO
ALTER TABLE PARRILLERO ADD CONSTRAINT PK_PARRILLERO PRIMARY KEY (CURP);
ALTER TABLE PARRILLERO ADD CONSTRAINT FK_PARRILLERO FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA EMPLEADO TAQUERO
ALTER TABLE TAQUERO ADD CONSTRAINT PK_TAQUERO PRIMARY KEY (CURP);
ALTER TABLE TAQUERO ADD CONSTRAINT FK_TAQUERO FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA EMPLEADO MESERO
ALTER TABLE MESERO ADD CONSTRAINT PK_MESERO PRIMARY KEY (CURP);
ALTER TABLE MESERO ADD CONSTRAINT FK_MESERO FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA EMPLEADO CAJERO
ALTER TABLE CAJERO ADD CONSTRAINT PK_CAJERO PRIMARY KEY (CURP);
ALTER TABLE CAJERO ADD CONSTRAINT FK_CAJERO FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA EMPLEADO TORTILLERO
ALTER TABLE TORTILLERO ADD CONSTRAINT PK_TORTILLERO PRIMARY KEY (CURP);
ALTER TABLE TORTILLERO ADD CONSTRAINT FK_TORTILLERO FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA EMPLEADO REPARTIDOR
ALTER TABLE REPARTIDOR ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY (CURP);
ALTER TABLE REPARTIDOR ADD CONSTRAINT FK_REPARTIDOR FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);
ALTER TABLE REPARTIDOR ADD CONSTRAINT CK_REPARTIDOR_LIC CHECK (LICENCIA IS NOT NULL);
ALTER TABLE REPARTIDOR ADD CONSTRAINT CK_REPARTIDOR_TR CHECK (TRANSPORTE IN ('AUTOMOVIL', 'MOTOCICLETA', 'BICICLETA'));

-- RESTRICCIONES TABLA SUCURSAL
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL);

-- RESTRICCIONES TABLA TRABAJAR_SUCURSAL
ALTER TABLE TRABAJAR_SUCURSAL ADD CONSTRAINT PK_TR_SUC PRIMARY KEY (ID_SUCURSAL, CURP);
ALTER TABLE TRABAJAR_SUCURSAL ADD CONSTRAINT FK_TR_ID FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);
ALTER TABLE TRABAJAR_SUCURSAL ADD CONSTRAINT FK_TR_CURP FOREIGN KEY (CURP) REFERENCES EMPLEADO(CURP);

-- RESTRICCIONES TABLA PRODUCTO
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO);

-- RESTRICCIONES TABLA TENER_PRODUCTO
ALTER TABLE TENER_PRODUCTO ADD CONSTRAINT PK_TN_PROD PRIMARY KEY (ID_SUCURSAL, ID_PRODUCTO);
ALTER TABLE TENER_PRODUCTO ADD CONSTRAINT FK_TN_IDS FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);
ALTER TABLE TENER_PRODUCTO ADD CONSTRAINT FK_TN_IDP FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);