
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodd
 */
public class VistaForm extends javax.swing.JFrame {
    
    /**
     * Creates new form VistaForm
     */
    public VistaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Metodo auxiliar para llenar las tablas
     * @param rs
     * @return
     * @throws SQLException 
     */
    public static DefaultTableModel buildTableModel(ResultSet rs) 
            throws SQLException {
        ResultSetMetaData datos = rs.getMetaData();
        // names of columns
        Vector<String> nombreColumnas = new Vector<String>();
        int numColumnas = datos.getColumnCount();
        for (int column = 1; column <= numColumnas; column++) {
            nombreColumnas.add(datos.getColumnName(column));
        }
        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndice = 1; columnIndice <= numColumnas; columnIndice++) {
                vector.add(rs.getObject(columnIndice));
            }
            data.add(vector);
    }

    return new DefaultTableModel(data, nombreColumnas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabelComputologos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenuItemParrilleros = new javax.swing.JMenuItem();
        jMenuItemTaqueros = new javax.swing.JMenuItem();
        jMenuItemCajeros = new javax.swing.JMenuItem();
        jMenuItemMeseros = new javax.swing.JMenuItem();
        jMenuItemTortilleros = new javax.swing.JMenuItem();
        jMenuItemRepartidores = new javax.swing.JMenuItem();
        jMenuSucursales = new javax.swing.JMenu();
        jMenuItemSucursales = new javax.swing.JMenuItem();
        jMenuConsumibles = new javax.swing.JMenu();
        jMenuItemConsumibles = new javax.swing.JMenuItem();
        jMenuItemEntradas = new javax.swing.JMenuItem();
        jMenuItemDelCazo = new javax.swing.JMenuItem();
        jMenuItemSopesHuaraches = new javax.swing.JMenuItem();
        jMenuItemEnchiladas = new javax.swing.JMenuItem();
        jMenuItemQuesos = new javax.swing.JMenuItem();
        jMenuItemEnsaladas = new javax.swing.JMenuItem();
        jMenuItemGringasQuecas = new javax.swing.JMenuItem();
        jMenuItemAlambres = new javax.swing.JMenuItem();
        jMenuItemHamburguesas = new javax.swing.JMenuItem();
        jMenuItemTacos = new javax.swing.JMenuItem();
        jMenuItemTortas = new javax.swing.JMenuItem();
        jMenuItemBebidas = new javax.swing.JMenuItem();
        jMenuItemPostres = new javax.swing.JMenuItem();
        jMenuSalsas = new javax.swing.JMenu();
        jMenuItemSalsas = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuPrivacidad = new javax.swing.JMenu();
        jMenuItemPrivacidad = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taquería");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 24)); // NOI18N
        jLabel1.setText("¡Bienvenido a Tacoste!");

        jLabelComputologos.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabelComputologos.setText("Computólogos AC.");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mano.png"))); // NOI18N
        jMenuClientes.setText("Clientes");
        jMenuClientes.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemClientes.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemClientes.setText("Mostrar Todo");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemClientes);

        jMenuBar1.add(jMenuClientes);

        jMenuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chef.png"))); // NOI18N
        jMenuEmpleados.setText("Empleados");
        jMenuEmpleados.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemEmpleados.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemEmpleados.setText("Mostrar Todo");
        jMenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemEmpleados);

        jMenuItemParrilleros.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemParrilleros.setText("Parrilleros");
        jMenuItemParrilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemParrillerosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemParrilleros);

        jMenuItemTaqueros.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemTaqueros.setText("Taqueros");
        jMenuItemTaqueros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTaquerosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemTaqueros);

        jMenuItemCajeros.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemCajeros.setText("Cajeros");
        jMenuItemCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCajerosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemCajeros);

        jMenuItemMeseros.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemMeseros.setText("Meseros");
        jMenuItemMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMeserosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemMeseros);

        jMenuItemTortilleros.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemTortilleros.setText("Tortilleros");
        jMenuItemTortilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTortillerosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemTortilleros);

        jMenuItemRepartidores.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemRepartidores.setText("Repartidores");
        jMenuItemRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepartidoresActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemRepartidores);

        jMenuBar1.add(jMenuEmpleados);

        jMenuSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mesa.png"))); // NOI18N
        jMenuSucursales.setText("Sucursales");
        jMenuSucursales.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemSucursales.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemSucursales.setText("Mostrar Todo");
        jMenuItemSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSucursalesActionPerformed(evt);
            }
        });
        jMenuSucursales.add(jMenuItemSucursales);

        jMenuBar1.add(jMenuSucursales);

        jMenuConsumibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pollo.png"))); // NOI18N
        jMenuConsumibles.setText("Consumibles");
        jMenuConsumibles.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemConsumibles.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemConsumibles.setText("Mostrar Todo");
        jMenuItemConsumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsumiblesActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemConsumibles);

        jMenuItemEntradas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemEntradas.setText("Entradas");
        jMenuItemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntradasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemEntradas);

        jMenuItemDelCazo.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemDelCazo.setText("Del Cazo");
        jMenuItemDelCazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDelCazoActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemDelCazo);

        jMenuItemSopesHuaraches.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemSopesHuaraches.setText("Sopes/Huaraches");
        jMenuItemSopesHuaraches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSopesHuarachesActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemSopesHuaraches);

        jMenuItemEnchiladas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemEnchiladas.setText("Enchiladas");
        jMenuItemEnchiladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnchiladasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemEnchiladas);

        jMenuItemQuesos.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemQuesos.setText("Quesos");
        jMenuItemQuesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuesosActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemQuesos);

        jMenuItemEnsaladas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemEnsaladas.setText("Ensaladas");
        jMenuItemEnsaladas.setActionCommand("");
        jMenuItemEnsaladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnsaladasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemEnsaladas);

        jMenuItemGringasQuecas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemGringasQuecas.setText("Gringas/Quecas/Volcanes");
        jMenuItemGringasQuecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGringasQuecasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemGringasQuecas);

        jMenuItemAlambres.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemAlambres.setText("Alambres");
        jMenuItemAlambres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlambresActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemAlambres);

        jMenuItemHamburguesas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemHamburguesas.setText("Hamburguesas");
        jMenuItemHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHamburguesasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemHamburguesas);

        jMenuItemTacos.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemTacos.setText("Tacos");
        jMenuItemTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTacosActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemTacos);

        jMenuItemTortas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemTortas.setText("Tortas");
        jMenuItemTortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTortasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemTortas);

        jMenuItemBebidas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemBebidas.setText("Bebidas");
        jMenuItemBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBebidasActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemBebidas);

        jMenuItemPostres.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemPostres.setText("Postres");
        jMenuItemPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPostresActionPerformed(evt);
            }
        });
        jMenuConsumibles.add(jMenuItemPostres);

        jMenuBar1.add(jMenuConsumibles);

        jMenuSalsas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Taza.png"))); // NOI18N
        jMenuSalsas.setText("Salsas");
        jMenuSalsas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemSalsas.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemSalsas.setText("Mostrar Todo");
        jMenuItemSalsas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalsasActionPerformed(evt);
            }
        });
        jMenuSalsas.add(jMenuItemSalsas);

        jMenuBar1.add(jMenuSalsas);

        jMenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cupcake.png"))); // NOI18N
        jMenuProductos.setText("Productos");
        jMenuProductos.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemProductos.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemProductos.setText("Mostrar Todo");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuItemProductos);

        jMenuBar1.add(jMenuProductos);

        jMenuPrivacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vela.png"))); // NOI18N
        jMenuPrivacidad.setText("Privacidad");
        jMenuPrivacidad.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N

        jMenuItemPrivacidad.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jMenuItemPrivacidad.setText("Mostrar");
        jMenuItemPrivacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrivacidadActionPerformed(evt);
            }
        });
        jMenuPrivacidad.add(jMenuItemPrivacidad);

        jMenuBar1.add(jMenuPrivacidad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(695, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelComputologos)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(jLabelComputologos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Informacion Clientes
     */
    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM CLIENTE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    /**
     * Informacion Empleado
     */
    private void jMenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM CLIENTE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemEmpleadosActionPerformed

    /**
     * Informacion Sucursal
     */
    private void jMenuItemSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSucursalesActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM SUCURSAL");
            JTable tabla = new JTable(buildTableModel(rs));
            JOptionPane.showMessageDialog(null, new JScrollPane(tabla));   
        }catch(Exception e){
        System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemSucursalesActionPerformed

    /**
     * Informacion Salsas
     */
    private void jMenuItemSalsasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalsasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM SALSA");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(750,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemSalsasActionPerformed

    private void jMenuItemPrivacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrivacidadActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("aviso.jpg"));
        JOptionPane.showMessageDialog(null, "", "Privacidad", JOptionPane.PLAIN_MESSAGE, icono);

    }//GEN-LAST:event_jMenuItemPrivacidadActionPerformed

    /**
     * Informacion Consumibles
     */
    private void jMenuItemConsumiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsumiblesActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(750,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemConsumiblesActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM PRODUCTO");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    /**
     * Informacion Parrilleros
     */
    private void jMenuItemParrillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemParrillerosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM PARRILLERO, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = PARRILLERO.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemParrillerosActionPerformed

    /**
     * Informacion Cajeros
     */
    private void jMenuItemCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCajerosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM CAJERO, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = CAJERO.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemCajerosActionPerformed

    /**
     * Informacion Repartidores
     */
    private void jMenuItemRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepartidoresActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM REPARTIDOR, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = REPARTIDOR.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemRepartidoresActionPerformed

    /**
     * Informacion Tortilleros 
     */
    private void jMenuItemTortillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTortillerosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM TORTILLERO, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = TORTILLERO.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemTortillerosActionPerformed

    /**
     * Informacion Meseros 
     */
    private void jMenuItemMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeserosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM MESERO, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = MESERO.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemMeserosActionPerformed

    /**
     * Informacion Taquero
     * @param evt 
     */
    private void jMenuItemTaquerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTaquerosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM TAQUERO, EMPLEADO\n" +
                "WHERE EMPLEADO.CURP = TAQUERO.CURP");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemTaquerosActionPerformed

    /**
     * Informacion Entradas
     */
    private void jMenuItemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntradasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM ENTRADAS, CONSUMIBLE\n" +
                "WHERE ENTRADAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemEntradasActionPerformed

    /**
     * Informacion Del Cazo
     */
    private void jMenuItemDelCazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDelCazoActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM DEL_CAZO, CONSUMIBLE\n" +
                "WHERE DEL_CAZO.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemDelCazoActionPerformed

    /**
     * Informacion Sopes_Huaraches
     * @param evt 
     */
    private void jMenuItemSopesHuarachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSopesHuarachesActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM SOPES_HUARACHES, CONSUMIBLE\n" +
                "WHERE SOPES_HUARACHES.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemSopesHuarachesActionPerformed

    /**
     * Informacion Enchiladas
     */
    private void jMenuItemEnchiladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnchiladasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM ENCHILADAS, CONSUMIBLE\n" +
                "WHERE ENCHILADAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemEnchiladasActionPerformed

    /**
     * Informacion Quesos
     * @param evt 
     */
    private void jMenuItemQuesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuesosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM QUESOS, CONSUMIBLE\n" +
                "WHERE QUESOS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemQuesosActionPerformed

    /**
     * Informacion Ensaladas
     * @param evt 
     */
    private void jMenuItemEnsaladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnsaladasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM ENSALADAS, CONSUMIBLE\n" +
                "WHERE ENSALADAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemEnsaladasActionPerformed

    /**
     * Informacion Gringas_Quecas_Volcanes
     * @param evt 
     */
    private void jMenuItemGringasQuecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGringasQuecasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM GRINGAS_QUECAS_VOLCANES, CONSUMIBLE\n" +
                "WHERE GRINGAS_QUECAS_VOLCANES.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemGringasQuecasActionPerformed

    /**
     * Informacion Alambres
     */
    private void jMenuItemAlambresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlambresActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM ALAMBRES, CONSUMIBLE\n" +
                "WHERE ALAMBRES.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemAlambresActionPerformed

    /**
     * Infomracion Hamburguesas
     */
    private void jMenuItemHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHamburguesasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM HAMBURGUESAS, CONSUMIBLE\n" +
                "WHERE HAMBURGUESAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemHamburguesasActionPerformed

    /**
     * Informacion Tacos
     * @param evt 
     */
    private void jMenuItemTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTacosActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM TACOS, CONSUMIBLE\n" +
                "WHERE TACOS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemTacosActionPerformed

    /**
     * Informacion Tortas
     */
    private void jMenuItemTortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTortasActionPerformed
       try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM TORTAS, CONSUMIBLE\n" +
                "WHERE TORTAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemTortasActionPerformed

    /**
     * Informacion Bebidas 
     */
    private void jMenuItemBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBebidasActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM BEBIDAS, CONSUMIBLE\n" +
                "WHERE BEBIDAS.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemBebidasActionPerformed

    /**
     * Informacion Postres
     */
    private void jMenuItemPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPostresActionPerformed
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            String url = "jdbc:oracle:thin:FBD/Amarok2136@localhost:1521:orcl";
            Connection db = DriverManager.getConnection(url);
            Statement sentencia = db.createStatement();
            ResultSet rs = sentencia.executeQuery("SELECT * FROM POSTRES, CONSUMIBLE\n" +
                "WHERE POSTRES.ID_CONSUMIBLE = CONSUMIBLE.ID_CONSUMIBLE");
            JTable tabla = new JTable(buildTableModel(rs));
            JScrollPane scrollpane = new JScrollPane(tabla);
            scrollpane.setPreferredSize(new Dimension(1000,500));
            JOptionPane.showMessageDialog(null, scrollpane);
        }catch(Exception e){
            System.out.println("Exception:" + e);
        }
    }//GEN-LAST:event_jMenuItemPostresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelComputologos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuConsumibles;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAlambres;
    private javax.swing.JMenuItem jMenuItemBebidas;
    private javax.swing.JMenuItem jMenuItemCajeros;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemConsumibles;
    private javax.swing.JMenuItem jMenuItemDelCazo;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemEnchiladas;
    private javax.swing.JMenuItem jMenuItemEnsaladas;
    private javax.swing.JMenuItem jMenuItemEntradas;
    private javax.swing.JMenuItem jMenuItemGringasQuecas;
    private javax.swing.JMenuItem jMenuItemHamburguesas;
    private javax.swing.JMenuItem jMenuItemMeseros;
    private javax.swing.JMenuItem jMenuItemParrilleros;
    private javax.swing.JMenuItem jMenuItemPostres;
    private javax.swing.JMenuItem jMenuItemPrivacidad;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemQuesos;
    private javax.swing.JMenuItem jMenuItemRepartidores;
    private javax.swing.JMenuItem jMenuItemSalsas;
    private javax.swing.JMenuItem jMenuItemSopesHuaraches;
    private javax.swing.JMenuItem jMenuItemSucursales;
    private javax.swing.JMenuItem jMenuItemTacos;
    private javax.swing.JMenuItem jMenuItemTaqueros;
    private javax.swing.JMenuItem jMenuItemTortas;
    private javax.swing.JMenuItem jMenuItemTortilleros;
    private javax.swing.JMenu jMenuPrivacidad;
    private javax.swing.JMenu jMenuProductos;
    private javax.swing.JMenu jMenuSalsas;
    private javax.swing.JMenu jMenuSucursales;
    // End of variables declaration//GEN-END:variables

}