/**
 * SCRIPT PARA BORRAR TODAS LAS TABLAS CREADAS EN EL SCRIPT ANTERIOR.
 * ES NECESARIO ESTE ORDEN PARA NO PRESENTAR PROBLEMAS CON 
 * LLAVES FORANEAS.
 */
DROP TABLE MEMBRESIA_BASICA;
DROP TABLE MEMBRESIA_PLUS;
DROP TABLE TENER;
DROP TABLE TOMAR_CLASE_SOCIO;
DROP TABLE TOMAR_CLASE_CLIENTE;
DROP TABLE COMPRAR_SOCIO;
DROP TABLE COMPRAR_CLIENTE;
DROP TABLE IMPARTIR_CLASE;
DROP TABLE OBTENER_PUNTOS;
DROP TABLE SISTEMA_PUNTOS;
DROP TABLE MEMBRESIA_PREMIUM;
DROP TABLE PRODUCTO;
DROP TABLE CLASE;
DROP TABLE SOCIO;
DROP TABLE TIPO_MEMBRESIA;
DROP TABLE MEMBRESIA;
DROP TABLE CLIENTE;
DROP TABLE ENTRENADOR;
DROP TABLE PERSONA;