-- TABLA PADRE PERSONA
-- HEREDA A SOCIO, CLIENTE, ENTRENADOR
CREATE TABLE PERSONA(
    ID_PERSONA NUMBER,
    NOMBRE VARCHAR (25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    EMAIL VARCHAR(25),
    EDAD DATE,
    SEXO VARCHAR(9),
    TELEFONO NUMBER(10)
);

-- TABLA SOCIO
CREATE TABLE SOCIO(
    ID_SOCIO NUMBER,
    NOMBRE VARCHAR (25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    EMAIL VARCHAR(25),
    EDAD DATE,
    SEXO VARCHAR(9),
    TELEFONO NUMBER(10),
    ID_PERSONA NUMBER,
    FEC_NAC DATE,
    PERSONA_CONTACTO VARCHAR(25),
    PUNTOS NUMBER
);

-- TABLA PERSONA_CONTACTO
CREATE TABLE PERSONA_CONTACTO(
    NOMBRE VARCHAR (25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    CONTACTO VARCHAR(30)
);

-- TABLA CLIENTE
CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR (25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    EMAIL VARCHAR(25),
    EDAD DATE,
    SEXO VARCHAR(9),
    TELEFONO NUMBER(10),
    ID_PERSONA NUMBER,
    FEC_NAC DATE,
    PERSONA_CONTACTO VARCHAR(25)
);

-- TABLA ENTRENADOR 
CREATE TABLE ENTRENADOR(
    ID_EMPLEADO NUMBER,
    NOMBRE VARCHAR (25),
    AP_PATERNO VARCHAR(25),
    AP_MATERNO VARCHAR(25),
    EMAIL VARCHAR(25),
    EDAD DATE,
    SEXO VARCHAR(9),
    TELEFONO NUMBER(10),
    ID_PERSONA NUMBER,
    ID_DIRECCION NUMBER
);

-- TABLA DIRECCION
CREATE TABLE DIRECCION(
    ID_DIRECCION NUMBER,
    CALLE VARCHAR(30),
    NUMERO NUMBER,
    COLONIA VARCHAR(25),
    CP NUMBER(5,0),
    DELEGACION VARCHAR(15)
);

-- TABLA MEMBRESIA
CREATE TABLE MEMBRESIA(
    ID_MEMBRESIA NUMBER,
    COSTO DECIMAL(5,2),
    ID_SOCIO NUMBER
);

-- TABLA MEMBRESIA_BASICA
CREATE TABLE MEMBRESIA_BASICA(
    ID_MEMBRESIA NUMBER,
    AREAS_ENTRENAMIENTO VARCHAR(80),
    REGADERAS VARCHAR(25)
);

-- TABLA MEMBRESIA_PLUS
CREATE TABLE MEMBRESIA_PLUS(
    ID_MEMBRESIA NUMBER,
    AREAS_ENTRENAMIENTO VARCHAR(80),
    REGADERAS VARCHAR(25),
    CASILLERO VARCHAR(10),
    ENTRENADOR VARCHAR(50)
);

-- TABLA MEMBRESIA_PREMIUM
CREATE TABLE MEMBRESIA_PREMIUM(
    ID_MEMBRESIA NUMBER,
    AREAS_ENTRENAMIENTO VARCHAR(80),
    REGADERAS VARCHAR(25),
    CASILLERO VARCHAR(10),
    ENTRENADOR VARCHAR(50),
    SAUNA VARCHAR(25),
    ESPECIALISTA_NUTRICION VARCHAR(25),
    PUNTOS NUMBER
);

-- TABLA CLASE
CREATE TABLE CLASE(
    NOMBRE_CLASE VARCHAR(25),
    ENTRENADOR VARCHAR(40),
    COSTO DECIMAL(5,2),
    ID_DIAS NUMBER,
    HORA_INICIO TIMESTAMP,
    HORA_FIN TIMESTAMP,
    PUNTOS NUMBER
);

-- TABLA PRODUCTO
CREATE TABLE PRODUCTO(
    NOMBRE_PRODUCTO VARCHAR(25),
    PRESENTACION VARCHAR(25),
    DESCRIPCION VARCHAR(50),
    EXISTENCIAS NUMBER,
    MARCA VARCHAR(25)
);

-- RELACION: SOCIO - TENER - MEMBRESIA
CREATE TABLE TENER(
    ID_MEMBRESIA NUMBER,
    ID_SOCIO NUMBER
);

-- RELACION: SOCIO - TOMAR - CLASES
CREATE TABLE TOMAR_CLASE_SOCIO(
    NOMBRE_CLASE VARCHAR(25),
    ENTRENADOR VARCHAR(40),
    ID_SOCIO NUMBER
);

-- RELACION: CLIENTE - TOMAR - CLASES
CREATE TABLE TOMAR_CLASE_CLIENTE(
    NOMBRE_CLASE VARCHAR(25),
    ENTRENADOR VARCHAR(40),
    ID_CLIENTE NUMBER
);

-- RELACION: SOCIO - COMPRAR - PRODUCTO
CREATE TABLE COMPRAR_SOCIO(
    ID_SOCIO NUMBER,
    NOMBRE_PRODUCTO VARCHAR(25),
    PRESENTACION VARCHAR(25)
);

-- RELACION: CLIENTE - COMPRAR - PRODUCTO
CREATE TABLE COMPRAR_CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE_PRODUCTO VARCHAR(25),
    PRESENTACION VARCHAR(25)
);

-- RELACION: ENTRENADOR - IMPARTE - CLASE
CREATE TABLE IMPARTIR_CLASE(
    NOMBRE_CLASE VARCHAR(25) NOT NULL,
    ENTRENADOR VARCHAR(40),
    ID_EMPLEADO NUMBER
);











